export const products = [
  { id: 1, name: "Wireless Mouse" },
  { id: 2, name: "Bluetooth Headphones" },
  { id: 3, name: "Gaming Keyboard" },
  { id: 4, name: "4K Monitor" },
  { id: 5, name: "Laptop Stand" },
  { id: 6, name: "USB-C Hub" },
  { id: 7, name: "Portable SSD" },
  { id: 8, name: "Smartphone Holder" },
  { id: 9, name: "Noise-Cancelling Earbuds" },
  { id: 10, name: "Webcam" },
  { id: 11, name: "External Hard Drive" },
  { id: 12, name: "Graphic Tablet" },
  { id: 13, name: "Wireless Charger" },
  { id: 14, name: "Mechanical Keyboard" },
  { id: 15, name: "Ergonomic Chair" },
  { id: 16, name: "Standing Desk" },
  { id: 17, name: "Smart Light Bulb" },
  { id: 18, name: "Fitness Tracker" },
  { id: 19, name: "Bluetooth Speaker" },
  { id: 20, name: "Smart Thermostat" },
  { id: 21, name: "Wi-Fi Range Extender" },
  { id: 22, name: "Drone" },
  { id: 23, name: "VR Headset" },
  { id: 24, name: "Electric Scooter" },
  { id: 25, name: "3D Printer" },
  { id: 26, name: "Running Shoes" },
  { id: 27, name: "Basketball Shoes" },
  { id: 28, name: "Casual Sneakers" },
  { id: 29, name: "Formal Leather Shoes" },
  { id: 30, name: "Hiking Boots" },
  { id: 31, name: "Sandals" },
  { id: 32, name: "Slip-On Shoes" },
  { id: 33, name: "High Heels" },
  { id: 34, name: "Loafers" },
  { id: 35, name: "Ankle Boots" },
  // Clothes
  { id: 36, name: "T-Shirt" },
  { id: 37, name: "Jeans" },
  { id: 38, name: "Hoodie" },
  { id: 39, name: "Jacket" },
  { id: 40, name: "Dress" },
  { id: 41, name: "Sweater" },
  { id: 42, name: "Blouse" },
  { id: 43, name: "Shorts" },
  { id: 44, name: "Skirt" },
  { id: 45, name: "Polo Shirt" },
  // Additional Products
  { id: 46, name: "Socks" },
  { id: 47, name: "Belt" },
  { id: 48, name: "Scarf" },
  { id: 49, name: "Gloves" },
  { id: 50, name: "Beanie" },
];
